
# **Re-structuring bio-database**

## *Mutating a new bio-database on PostgreSQL* 

The bio-database of ODB had been constructed since 2009 and completely set-up on Microsoft SQL Server since 2015. The data curation is basically done by a Microsoft C# program. These protocols of data curation was documented in 圖輯. For developing an open cross-platform framework for web APIs of bio-database, first, we mutated a bio-database on PostgreSQL, i.e., exported from SQL Server, and then re-imported to a new database by using PostgreSQL.

<br>

::: {.infobox data-latex=""}

:::: {.box_main custom-style="box1_main"}
Box2.1
::::

:::: {.box_submain custom-style="box1_sect"}
Why not just use original Microsoft SQL Server as backend database for developing APIs of bio-database?
::::

:::: {custom-style="box1"}
  &check; SQL Server is a commercial software with annual license fees.

  &check; SQL Server is suited for the Microsoft Server based framework, but not for an open cross-platform framework.  
::::

:::: {.box_submain custom-style="box1_sect"}
Why choose PostgreSQL?
::::

:::: {custom-style="box1"}
  &check; PostgreSQL is a powerful open-source object-relational database systems.

  &check; PostgreSQL can be well integrated in Geographic Information System (GIS) applications by its PostGIS extension.
  - It’s an important reason why we choose PostgreSQL. Most of APIs in ODB are used to develop GIS related applications.
::::

:::

<br>

As a backend database for API in production, we do not need some columns of variables originally in SQL Server (Fig. 2a) that used to remark some quality control (QC) issues. So when mutating the bio-database on PostgreSQL, we also did some simplifications for database schema (Fig. 2b). Roughly speaking, we left the “remark_xxx” or “flag_xxx” columns in SQL Server only, and in PostgreSQL, re-arranged the tables to make frequently-used variables more easily be accessed in table “cast_site” (site information) and “taxa_data” (abundance data of taxonomic groups). Another important modification is to construct classification of taxonomic groups in table ‘taxon_group” that can help us in analytical statistics among taxonomic groups when using bio-database data. The major parts of schema for bio-database on PostgreSQL include:
taxon_group: 

1. cast_site:

2. c00_cast_tbl:

3. t00_taxa_tbl:

4. taxa_data:

``` {r sqlServer2postgres}
# NOW in Ubuntu, this driver is not support old SQL Serve 2008 R2. It only works in Windows
# if on Ubuntu, the driver setting is in /etc/odbcinst.ini, e.g. driver={ODBC Driver 18 for SQL Server}
library(RODBC)
ms_conn <- odbcDriverConnect(paste0('driver={SQL Server};server=', sqlServerHost,  ';database=', sqlServerDB, ';uid=', sqlServerUser, ';pwd=', sqlServerPass))

```